### PR TITLE
Fixlink

### PR DESCRIPTION
**Pull request by dimpase**
fix the order of args in the linker call
    
libs to link should be at the end

### CODE REVIEW

**Comment by fingolfin** [comment]
This has conflicts, and seems to contain unrelated changes?

**Comment by fingolfin** [comment]
I've applied the link order fix manually, thank you!

**Comment by dimpase** [comment]
That's your branch rebased over the up to date main branch (and the fix for the link). Sorry for not mentioning this in the 1st place.

**Comment by fingolfin** [comment]
yeah but that's not how PRs work... if you rebase like that, the PR is useless, as it can't be merged

**Comment by dimpase** [comment]
you guys could promote me so that I could add commits to PRs directly, rather than going via PR to PR route...

**Comment by fingolfin** [comment]
I don't own the Semigroups repository so I can't do that. In any case, it is also not necessary if you just use the PR review feature, then you can suggest changes inline and I can accept them with a click. Or you have some patience and wait till the weekend is over then I'll apply changes manually, too ;-)

**Pull request closed without merging**
